# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.idea
  | \.pytest_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[flake8]
ignore = E203
max-line-length = 79
